version: '3.8'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}nspm-client-fe:latest
    container_name: nspm-client-fe
    ports:
      - "5000:80"
