version: '3.3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always 
    image: ${DOCKER_REGISTRY}my-angular-app:latest
    container_name: my-angular-app
    restart: always
    ports:
      - "5002:80"
