---
- name: Deploy Angular App
  hosts: localhost
  tasks:
    - name: Copy Angular app files
      copy:
        src: "{{ mint_client_src }}"
        dest: "/usr/share/nginx/html"

    - name: Build Docker image
      command: docker build -t my-angular-app -f {{ workspace_dir }}/Dockerfile {{ workspace_dir }}

    - name: Start Docker Compose
      command: docker-compose -f {{ ansible_playbook_dir }}/ansible/docker-compose.yml up -d --force-recreate

  vars:
    mint_client_src: "/mint_client/dist/mint-client/"
    workspace_dir: "/var/lib/jenkins/workspace/ngmintclient"
